name: bebro
description: A new Flutter project.

version: 1.0.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 3.0.3
  #Toast
  oktoast: ^2.3.1+1
  extended_image: ^0.7.1
  image_picker: ^0.6.1+8
  image_picker_saver: ^0.3.0
  image_editor: any
  multi_image_picker: ^4.6.1
  shared_preferences: ^0.5.3+1
  #输出打印好看一点
  logger: ^0.7.0+2
  provider: ^4.0.4
  android_intent: ^0.3.4+7
  flutter_easyrefresh: ^2.0.4
  #屏幕适配
  flutter_screenutil: ^1.1.0
  extended_nested_scroll_view: ^0.4.0
  #加载动画
  flutter_spinkit: ^4.1.2
  #uuid: ^2.0.4
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  qr_flutter: ^3.1.0
  r_scan: 0.1.4+1
  url_launcher: ^5.4.2
  permission_handler: ^4.4.0
  extended_text: ^0.7.1
  loading_more_list: 1.0.5
  flutter_icons: ^1.0.0+1
  extended_text_field: ^0.5.0
  open_file: ^2.1.1
  path_provider: ^1.5.0
  package_info: 0.4.0+10
  flutter_image_compress: ^0.6.5+1
  assets_audio_player: ^1.2.3
  sticky_headers: "^0.1.8"
  web_socket_channel: ^1.1.0
  flui: ^0.9.0
  cupertino_icons: ^0.1.2
  extended_list: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^ 1.0.0
  json_serializable: ^3.2.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/images/emotionIcons/

  fonts:
    - family: myicon
      fonts:
        - asset: assets/fonts/myicon.ttf
    - family: "chocolate"
      fonts:
          - asset: assets/fonts/chocolate.ttf
    - family: "JetBrains Mono"
      fonts:
          - asset: assets/fonts/JetBrainsMono-Regular.ttf