name: bebro
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: 3.0.3
  #Toast
  oktoast: ^2.3.1+1
  extended_image: ^0.7.1
  image_picker: ^0.6.1+8
  image_picker_saver: ^0.3.0
  image_editor: any
  multi_image_picker: ^4.6.1
  shared_preferences: ^0.5.3+1
  #输出打印好看一点
  logger: ^0.7.0+2
  provider: ^3.1.0
  android_intent: ^0.3.4+7
  flutter_easyrefresh: ^2.0.4
  json_annotation: ^ 3.0.0
  #屏幕适配
  flutter_screenutil: ^1.0.2
  extended_nested_scroll_view: ^0.4.0
  #加载动画
  flutter_spinkit: ^4.1.2
  #uuid: ^2.0.4
  flutter_picker:
    git: git://github.com/yangyxd/flutter_picker.git
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^ 1.0.0
  json_serializable: ^3.2.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  uses-material-design: true

  assets:
    - images/flutter_logo.png
    - images/ma.png
    - images/back.jpg

  fonts:
    - family: dongqing
      fonts:
        - asset: fonts/dongqingW3.otf

    - family: arial
      fonts:
        - asset: fonts/Arial.ttf

    - family: myicon
      fonts:
        - asset: fonts/myicon.ttf